# validating k8s yaml
# https://learnk8s.io/validating-kubernetes-yaml
# deploy an echo service then test it
# kubectl apply -f <this>.yaml
# kubectl port-forward svc/http-echo 8080:5678
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: jxlwqq/http-echo
        args: ["--text", "hello-world"]
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo
spec:
  ports:
  - port: 5678 
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-echo
