---
apiVersion: v1
kind: Service
metadata:
  name: example-pod
spec:
  ports:
    - name: 81-tcp
      port: 810
      protocol: TCP
      targetPort: 80
  selector:
    com.docker.project: example-pod
  type: LoadBalancer
status:
  loadBalancer: {}
---
kind: Pod
apiVersion: v1
metadata:
  labels:
    com.docker.project: example-pod
  name: example-pod
spec:
  containers:
    - image: nginx
      name: example-container
