# http://localhost:81/swagger.json
# http://localhost:81/
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  ports:
    - name: 81-tcp
      port: 81
      protocol: TCP
      targetPort: 9898
  selector:
    com.docker.project: podinfo
  type: LoadBalancer
status:
  loadBalancer: {}
---
kind: Pod
apiVersion: v1
metadata:
  labels:
    com.docker.project: podinfo
  name: podinfo
spec:
  containers:
    - image: ghcr.io/stefanprodan/podinfo
      name: podinfo-container
